"""create users table

Revision ID: f125557667c3
Revises: c27bafadcdd0
Create Date: 2025-06-01 22:46:20.196536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f125557667c3'
down_revision = 'c27bafadcdd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
